### ISSUE TITLE
<<< Did not place order because available volume too low. >>>

### ISSUE THREAD

**Issue by algpet** [miguelmota/python-etherdelta#2]
I spend few hours trying to post order with 
client.create_order + client.post
All I get back is "Did not place order because available volume too low." message.
googling this message shows that few ppl have such error as well. Anyone was able to get past this one ?

**Comment by miguelmota** [comment]
@algpet can you show us the entire code snippet to better help? Wondering if it's just misconfiguration or a problem with EtherDelta. Thanks

**Comment by miguelmota** [comment]
@algpet please reopen issue if problem persists
