### ISSUE TITLE
FileNoteFoundError: Can't find token.json

### ISSUE THREAD

**Issue by vikramarun** [miguelmota/python-etherdelta#3]
Am I missing a dependency or something here when calling the Client function? Here is the error message:

Traceback (most recent call last):
  File "C:\Users\Vik\eclipse-workspace\LedgerCapital\EtherDelta\__init__.py", line 2, in <module>
    client = etherdelta.Client()
  File "C:\Users\Vik\AppData\Local\Programs\Python\Python36-32\lib\site-packages\etherdelta\__init__.py", line 33, in __init__
    with open(os.path.join(os.path.dirname(__file__), '../contracts/token.json'), 'r') as token_abi_definition:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Vik\\AppData\\Local\\Programs\\Python\\Python36-32\\lib\\site-packages\\etherdelta\\../contracts/token.json'

On the following simple code:

import etherdelta 
client = etherdelta.Client()
account = '0x85E4B84D784eE9eEB7489F0B0c66B343AF2a0BE5'
bal = client.get_eth_balance(account)
print(bal)

Thanks for the help. Appreciate the work.

**Comment by lcvass** [comment]
Same issue here. All dependencies are installed.

Edit:  placing 'contracts' folder from this respository alongside the etherdelta folder seems to fix this. Though I'm still having issues, tickers return blank.

**Comment by vikramarun** [comment]
lucascvassalli, that worked thanks. I'm not having an error with tickers, but it always give me a "Deferred" error such as: <Deferred at 0x70b8eb0>.

Think the Etherdelta API might be down.

**Comment by miguelmota** [comment]
@vikramarun @lucascvassalli JSON ABI dependency is fixed

Try reinstalling

```bash
pip uninstall etherdelta
pip install etherdelta
```

or

```bash
pip3 install git+git://github.com/miguelmota/py-etherdelta.git
```

EtherDelta recently changed their websocket endpoint which may of been breaking things.

After reinstalling, try something simple like

```python
import etherdelta

client = etherdelta.Client()
token_addr = '0x0d8775f648430679a709e98d2b0cb6250d2887ef'
orders = client.get_buy_orderbook(token_addr)
```

and let me know if you still have problems

Thanks for reporting!

**Comment by vikramarun** [comment]
Awesome, that partly works now. Thanks for the stuff you've been doing on the project.

I get an output but its a deferred object from twisted... for example the code you sent gives me the following:

<Deferred at 0x863c070 current result: ........
of the type twisted.internet.defer.Deferred.

Any ideas? Figure it might just be a problem with the socket still

**Comment by miguelmota** [comment]
@vikramarun I switched deferreds for generators so you shouldn't see that now

Try updating and see if it works

```
pip3 install git+git://github.com/miguelmota/py-etherdelta.git
```

Sorry for my lack of python knowledge 😅

**Comment by miguelmota** [comment]
@vikramarun please open issue if you continue to have problems
