### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by blaaaaaaa** [miguelmota/python-etherdelta#4]
Hello,
 I struggle with the requirements/installation process. Cant find big-red and setupfiles also not goong through or is it the wrong requirements file I am using (python 2.7, 3.5, 3,6 trief? I am on mac, but fresh ubuntu available as well, what do I need from a fresh install to get it running? Help would be very appreciated!

**Comment by miguelmota** [comment]
@blaaaaaaa hi, just made some updates. Try reinstalling and let me it works for you 

```
pip3 uninstall etherdelta
pip3 install etherdelta
```

or 

```
pip3 install git+git://github.com/miguelmota/py-etherdelta.git
```
